Repository react-native-village/react-native-init, pull requests merged in 2022-12, with the labels that each got.

#128 feat(code style): eslint, prettier, absolute import
  Joker/.eslintignore
  Joker/.eslintrc.js
  Joker/.eslintrc.json
  Joker/App.tsx
  Joker/babel.config.js
  Joker/index.js
  Joker/package.json
  Joker/src/components/modals/test.tsx
  Joker/src/helpers/modal.tsx
  Joker/src/screens/modals.tsx
  Joker/src/variables.ts
  Joker/tsconfig.json
  Joker/yarn.lock
Labels: dependencies, CI/CD

#127 init(ci/cd): workflow
  .github/workflows/main.yml
  Joker/.eslintignore
  Joker/__tests__/App-test.tsx
  Joker/ios/Podfile.lock
  Joker/package.json
Labels: logic, CI/CD

#129 feat(graphql): codegenerate, docs, use auth token in query
  Joker/.babelrc
  Joker/.eslintrc.json
  Joker/README.md
  Joker/fileExtensions.d.ts
  Joker/graphql.config.yaml
  Joker/ios/Joker.xcodeproj/project.pbxproj
  Joker/package.json
  Joker/src/app-with-providers.tsx
  Joker/src/generated/graphql.ts
  Joker/src/graphql/user-info.graphql
  Joker/src/screens/tab-screen5.tsx
  Joker/src/services/github-auth.ts
  Joker/src/variables.ts
  Joker/yarn.lock
Labels: dependencies, no-QA, api

#133 add: lens
  Joker/.gitignore
  Joker/graphql.config.ts
  Joker/graphql.config.yaml
  Joker/package.json
  Joker/src/app-with-providers.tsx
  Joker/src/generated/graphql-github.ts
  Joker/src/generated/graphql-lens.ts
  Joker/src/graphql/github/index.ts
  Joker/src/graphql/github/user-info.graphql
  Joker/src/graphql/lens/explore-profiles.graphql
  Joker/src/graphql/lens/index.ts
  Joker/src/helpers/index.ts
  Joker/src/helpers/modal.ts
  Joker/src/screens/tab-screen2.tsx
  Joker/src/services/github-auth.ts
  Joker/src/variables.ts
  Joker/yarn.lock
Labels: dependencies, logic, api

#136 feat(moralis): server and request
  .DS_Store
  Joker/src/screens/tab-screen3.tsx
  joker-moralis-server/.env.example
  joker-moralis-server/.gitignore
  joker-moralis-server/package.json
  joker-moralis-server/src/dapp.ts
  joker-moralis-server/src/request/getDemoData.ts
  joker-moralis-server/src/request/index.ts
  joker-moralis-server/yarn.lock
Labels: logic, blockchain, api
